#!/usr/bin/env python3

# nvd - Nix/NixOS package version diff tool
#
# Copyright 2021-2024 Bryan Gardiner <bog@khumba.net>
# Copyright 2024 Felix Uhl <nvd@mail.felix-uhl.de>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See the nvd(1) man page for user-facing docs.

# Package install state (by pname):
# I: Installed (unchanged)
# A: Added to closure
# R: Removed from closure
# U: Upgrade
# D: Downgrade
# C: Changed versions or selection state

# Package selection state (by pname):
# +: Package is newly selected in environment.systemPackages.
# -: Package is newly unselected.
# *: Package is selected; state unchanged.
# .: Not in environment.systemPackages; dependency.
# l: Selected package set only available on the left; not selected there.
# L: Selected package set only available on the left; selected there.
# r: Selected package set only available on the right; not selected there.
# R: Selected package set only available on the right; selected there.

import argparse
import fnmatch
import os
import os.path
import re
import subprocess
import sys
from abc import abstractmethod
from collections.abc import Collection
from functools import cmp_to_key, total_ordering
from itertools import pairwise
from pathlib import Path
from signal import SIGPIPE, SIG_DFL, signal
from subprocess import PIPE
from typing import Iterable, List, Optional, Union

signal(SIGPIPE, SIG_DFL)  # Python handles SIGPIPE improperly by default.

NVD_VERSION = "0.2.4"

NIX_BIN_DIR = None
USE_NIX_COMMAND_FEATURE = False  # Whether to explicitly enable the nix-command feature.
USE_COLOUR = False

SGR_RESET = 0
SGR_BOLD = 1
SGR_FG = 30
SGR_BG = 40
SGR_BRIGHT = 60  # Add to SGR_FG or SGR_BG.
SGR_BLACK = 0
SGR_RED = 1
SGR_GREEN = 2
SGR_YELLOW = 3
SGR_BLUE = 4
SGR_MAGENTA = 5
SGR_CYAN = 6
SGR_WHITE = 7

def sgr(*args):
    assert all(isinstance(arg, int) for arg in args), \
        "sgr() args must all be integers: {args!r}"
    if not USE_COLOUR:
        return ""
    return "\x1b[" + ";".join(str(arg) for arg in args) + "m"

INST_INSTALLED = "I"
INST_ADDED = "A"
INST_REMOVED = "R"
INST_UPGRADED = "U"
INST_DOWNGRADED = "D"
INST_CHANGED = "C"

SEL_SELECTED = "*"
SEL_UNSELECTED = "."
SEL_NEWLY_SELECTED = "+"
SEL_NEWLY_UNSELECTED = "-"
# There's no way to reach these selection states currently, since selected sets
# are always computed.
SEL_LEFT_ONLY_SELECTED = "L"
SEL_LEFT_ONLY_UNSELECTED = "l"
SEL_RIGHT_ONLY_SELECTED = "R"
SEL_RIGHT_ONLY_UNSELECTED = "r"
SEL_NO_SELECTED_SETS = ""

NIX_STORE_PATH_REGEX = re.compile(r"^/nix/store/[a-z0-9]+-(.+?)(-([0-9].*?))?(\.drv)?$")
PROFILE_LINK_REGEX = re.compile(r"^(?P<profile>.+)-(?P<version>[0-9]+)-link$")

ALPHANUM_RE = re.compile(r"\w")  # Alternatively [0-9a-zA-Z] would work.

DIGIT_RE = re.compile("[0-9]")

VERSION_HIGHLIGHT_NONE = "none"
VERSION_HIGHLIGHT_BOLD = "bold"
VERSION_HIGHLIGHT_XMAS = "xmas"

VERSION_HIGHLIGHT_DEFAULT = VERSION_HIGHLIGHT_XMAS

ALL_VERSION_HIGHLIGHTS = (
    VERSION_HIGHLIGHT_NONE,
    VERSION_HIGHLIGHT_BOLD,
    VERSION_HIGHLIGHT_XMAS,
)

def raise_arg(e):
    raise e

@total_ordering
class ProfileVersion:
    def __init__(self, path: Path):
        match = PROFILE_LINK_REGEX.match(str(path))
        assert match is not None, f"Couldn't parse profile link: {path}"
        self._path = path.resolve()
        self._version = int(match.group("version"))

    def __lt__(self, other):
        if not isinstance(other, ProfileVersion):
            return NotImplemented

        return self._version < other._version

    def __eq__(self, other):
        if not isinstance(other, ProfileVersion):
            return NotImplemented

        return self._version == other._version

    def path(self):
        return self._path

    def version(self):
        return self._version

class StorePath:
    def __init__(self, path: Union[str, Path]):
        assert str(path).startswith("/nix/store/"), \
            f"Doesn't start with /nix/store/: {str(path)!r}"
        self._path = Path(path)

    def __str__(self) -> str:
        return f"<StorePath: {self._path}>"

    def __hash__(self):
        return hash(self._path)

    def __eq__(self, other):
        return type(other) is StorePath and self._path == other._path

    def path(self) -> Path:
        return self._path

    def to_base_path(self) -> "StorePath":
        return StorePath(os.path.join(*self._path.parts[0:4]))

# For the version comparison algorithm, see:
# https://nix.dev/manual/nix/stable/command-ref/nix-env/upgrade#versions

@total_ordering
class VersionChunk:
    def __init__(self, chunk_value: Union[int, str]):
        assert isinstance(chunk_value, int) or isinstance(chunk_value, str)
        self._chunk_value = chunk_value

    def __str__(self):
        return repr(self._chunk_value)

    def __lt__(self, other):
        if not isinstance(other, VersionChunk):
            return NotImplemented

        x = self._chunk_value
        y = other._chunk_value
        x_int = isinstance(x, int)
        y_int = isinstance(y, int)
        if x_int and y_int:
            return x < y
        elif (x == "" and y_int) or (x == "pre" and y != "pre"):
            return True
        elif (x_int and y == "") or (y == "pre" and x != "pre"):
            return False
        elif x_int:  # y is a string
            return False
        elif y_int:  # x is a string
            return True
        else:  # both are strings
            return x < y

    def __eq__(self, other):
        if not isinstance(other, VersionChunk):
            return NotImplemented

        return self._chunk_value == other._chunk_value

@total_ordering
class Version:
    def __init__(self, text: Optional[str]):
        if text is None:
            text = ""

        self._text: str = text

        self._chunks: list[VersionChunk] = []
        while text != "":
            first_char = text[0]
            if first_char.isdigit():
                last = 0
                while last + 1 < len(text) and text[last + 1].isdigit():
                    last += 1
                self._chunks.append(VersionChunk(int(text[0 : last + 1])))
                text = text[last + 1:]
            elif first_char.isalpha():
                last = 0
                while last + 1 < len(text) and text[last + 1].isalpha():
                    last += 1
                self._chunks.append(VersionChunk(text[0 : last + 1]))
                text = text[last + 1:]
            else:
                last = 0
                while last + 1 < len(text) and not text[last + 1].isdigit() and not text[last + 1].isalpha():
                    last += 1
                # No chunk append here, only care about alnum runs.
                text = text[last + 1:]

    def __eq__(self, other):
        if not isinstance(other, Version):
            return NotImplemented
        return self._chunks == other._chunks

    def __lt__(self, other):
        if not isinstance(other, Version):
            return NotImplemented
        return self._chunks < other._chunks

    def text(self) -> str:
        """Returns the version string, empty (not None) if there is no version."""
        return self._text

class Package:
    def __init__(self, *, pname: str, version: Version, store_path: StorePath):
        assert isinstance(pname, str), f"Not a string: {pname!r}"
        assert isinstance(version, Version), f"Not a Version: {version!r}"
        assert isinstance(store_path, StorePath), f"Not a StorePath: {store_path!r}"
        self._pname = pname
        self._version = version
        self._store_path = store_path

    def pname(self) -> str:
        return self._pname

    def version(self) -> Version:
        return self._version

    def store_path(self) -> StorePath:
        return self._store_path

class PackageSet:
    def __init__(self, packages: list[Package], store_paths: list[str]):
        assert isinstance(packages, list)
        assert all(isinstance(package, Package) for package in packages)

        self._packages = packages
        self._store_paths = store_paths

        # Unordered map from pnames to available package versions, in ascending
        # version order.
        self._packages_by_pname: dict[str, list[Package]] = {}
        for entry in packages:
            self._packages_by_pname.setdefault(entry.pname(), []).append(entry)

        for pkgs in self._packages_by_pname.values():
            pkgs.sort(key=lambda p: p.version())

    @staticmethod
    def from_direct_dependencies(path: Path) -> "PackageSet":
        return PackageSet.from_nix_query(["--references", str(path)])

    @staticmethod
    def from_closure(path: Path) -> "PackageSet":
        return PackageSet.from_nix_query(["--requisites", str(path)])

    @staticmethod
    def from_nix_query(nix_query_args: list[str]) -> "PackageSet":
        result_paths_str: str = subprocess.run(
            [make_nix_bin_path("nix-store"), "--query"] + nix_query_args,
            stdout=PIPE,
            text=True,
            check=True,
        ).stdout.rstrip("\n")

        result_paths: list[str] = \
            result_paths_str.split("\n") if result_paths_str else []

        packages = []
        for result_path in result_paths:
            pname, version = parse_pname_version(result_path)
            packages.append(Package(
                pname=pname,
                version=Version(version),
                store_path=StorePath(result_path),
            ))

        return PackageSet(packages, result_paths)

    def contains_pname(self, pname: str) -> bool:
        return pname in self._packages_by_pname

    def all_pnames(self):
        return self._packages_by_pname.keys()

    def all_store_paths(self):
        return iter(self._store_paths)

    def get_pname_packages(self, pname: str) -> list[Package]:
        return self._packages_by_pname.get(pname, [])

    def get_pname_versions(self, pname: str) -> list[Version]:
        return [pkg.version() for pkg in self.get_pname_packages(pname)]

class PackageSetPair:
    def __init__(
            self,
            left_set: Optional[PackageSet],
            right_set: Optional[PackageSet]
    ):
        assert left_set is None or isinstance(left_set, PackageSet)
        assert right_set is None or isinstance(right_set, PackageSet)
        self._left_set = left_set
        self._right_set = right_set

    def get_left_set(self) -> Optional[PackageSet]:
        return self._left_set

    def get_right_set(self) -> Optional[PackageSet]:
        return self._right_set

    def get_selection_state(self, pname: str) -> str:
        left_set = self._left_set
        right_set = self._right_set

        if left_set is not None and right_set is not None:
            in_left_set = left_set.contains_pname(pname)
            in_right_set = right_set.contains_pname(pname)
            selection_state_str = [
                SEL_UNSELECTED,
                SEL_NEWLY_UNSELECTED,
                SEL_NEWLY_SELECTED,
                SEL_SELECTED,
            ][int(in_left_set) + 2 * int(in_right_set)]
        elif left_set is not None:
            in_left_set = left_set.contains_pname(pname)
            selection_state_str = [
                SEL_LEFT_ONLY_UNSELECTED,
                SEL_LEFT_ONLY_SELECTED,
            ][int(in_left_set)]
        elif right_set is not None:
            in_right_set = right_set.contains_pname(pname)
            selection_state_str = [
                SEL_RIGHT_ONLY_UNSELECTED,
                SEL_RIGHT_ONLY_SELECTED,
            ][int(in_right_set)]
        else:
            selection_state_str = SEL_NO_SELECTED_SETS

        return selection_state_str

    def is_selection_state_changed(self, pname: str) -> bool:
        in_left_set = \
            self._left_set is not None and \
            self._left_set.contains_pname(pname)
        in_right_set = \
            self._right_set is not None and \
            self._right_set.contains_pname(pname)
        return in_left_set != in_right_set

def cmp(a, b) -> int:
    return (a > b) - (a < b)

class PackageListEntry:
    def __init__(
        self,
        *,
        left_packages: list[Package],
        right_packages: Optional[list[Package]],
    ) -> None:
        assert left_packages or right_packages, "No packages given."

        self._left_packages = left_packages
        self._right_packages = right_packages

    def get_pname(self) -> str:
        if self._right_packages:
            return self._right_packages[0].pname()
        else:
            return self._left_packages[0].pname()

    def get_left_packages(self) -> list[Package]:
        return self._left_packages

    def get_right_packages(self) -> Optional[list[Package]]:
        return self._right_packages

class PackageListEntryComparator:
    @abstractmethod
    def name(self) -> str:
        pass

    @abstractmethod
    def cmp_packages(self, a: PackageListEntry, b: PackageListEntry) -> int:
        pass

    def reversed(self) -> "PackageListEntryComparator":
        return PackageListEntryReverseComparator(self)

class PackageListEntryReverseComparator(PackageListEntryComparator):
    def __init__(self, delegate: PackageListEntryComparator):
        self._delegate = delegate

    def name(self) -> str:
        return "-" + self._delegate.name()

    def cmp_packages(self, a: PackageListEntry, b: PackageListEntry) -> int:
        return self._delegate.cmp_packages(b, a)

    def reversed(self) -> PackageListEntryComparator:
        return self._delegate

class PackageListEntryNameComparator(PackageListEntryComparator):
    def name(self) -> str:
        return "name"

    def cmp_packages(self, a: PackageListEntry, b: PackageListEntry) -> int:
        return cmp(
            a.get_left_packages()[0].pname(),
            b.get_left_packages()[0].pname(),
        )

ALL_SORTS: dict[str, PackageListEntryComparator] = {
    sk.name(): sk
    for sk in (
        # The first one listed here is the default.
        PackageListEntryNameComparator(),
    )
}

DEFAULT_SORT: PackageListEntryComparator = next(iter(ALL_SORTS.values()))

class PackageListEntryCombinedComparator(PackageListEntryComparator):
    def __init__(self, comparators: Iterable[PackageListEntryComparator]):
        self._comparators = list(comparators)

    @staticmethod
    def from_str(val: Optional[str]):
        if not val:
            val = DEFAULT_SORT.name()

        comparators: list[PackageListEntryComparator] = []

        specs = val.split(",")
        for spec in specs:
            reverse = spec.startswith("-")
            if reverse:
                spec = spec[1:]

            comparator = ALL_SORTS.get(spec, None)
            if comparator is None:
                sys.stderr.write(f"nvd: Error, unknown sort key '{spec}'.\n")
                sys.exit(1)

            if reverse:
                comparator = comparator.reversed()

            comparators.append(comparator)

        return PackageListEntryCombinedComparator(comparators)

    def name(self) -> str:
        return ",".join(c.name() for c in self._comparators)

    def cmp_packages(self, a: PackageListEntry, b: PackageListEntry) -> int:
        for comparator in self._comparators:
            result = comparator.cmp_packages(a, b)
            if result != 0:
                return result

        return 0

    def reversed(self) -> PackageListEntryComparator:
        return PackageListEntryCombinedComparator(c.reversed() for c in self._comparators)

def parse_pname_version(path: str) -> tuple[str, Optional[str]]:
    base_path = str(StorePath(path).to_base_path().path())

    match = NIX_STORE_PATH_REGEX.search(base_path)
    assert match is not None, f"Couldn't parse path: {path}"

    pname = match.group(1)
    version = match.group(3)

    return pname, version

def render_versions(
        version_list: list[Version],
        *,
        colour: bool,
        version_highlight: str,
        highlight_from_pos: Optional[int] = None,
        is_right: bool = False,
) -> str:
    if version_list == []:
        return "<no versions>"

    items = []

    version_list = list(version_list)  # Create a copy we can modify.
    while version_list != []:
        version = version_list.pop()
        count = 1
        while version_list != [] and version_list[-1] == version:
            version_list.pop()
            count += 1

        text = version.text()
        if text == "":
            text = "<none>"
        elif colour:  # (Don't apply colour to <none>.)
            if highlight_from_pos is None:
                text = sgr(SGR_FG + SGR_YELLOW) + text + sgr(SGR_RESET)
            else:
                if version_highlight == VERSION_HIGHLIGHT_XMAS:
                    sgr_highlight = sgr(SGR_FG + (SGR_GREEN if is_right else SGR_RED))
                elif version_highlight == VERSION_HIGHLIGHT_BOLD:
                    sgr_highlight = sgr(SGR_BOLD)
                elif version_highlight == VERSION_HIGHLIGHT_NONE:
                    sgr_highlight = ""
                else:
                    raise RuntimeError(
                        f"Internal error, unknown version_highlight: {version_highlight!r}"
                    )

                text = \
                    sgr(SGR_FG + SGR_YELLOW) \
                    + text[0:highlight_from_pos] \
                    + sgr_highlight \
                    + text[highlight_from_pos:] \
                    + sgr(SGR_RESET)

        if count == 1:
            items.append(text)
        else:
            items.append(text + f" x{count}")

    items.reverse()
    return ", ".join(items)

def print_packages(
    *,
    pnames: Collection[str],
    sort_comparator: Optional[PackageListEntryComparator],
    version_highlight: str,
    selected_sets: PackageSetPair,
    left_package_set: PackageSet,
    right_package_set: Optional[PackageSet] = None,
    fixed_install_state: Optional[str] = None,
    no_version_suffix_highlight: bool = False,
):
    assert (right_package_set is None) != (fixed_install_state is None), \
        "Expect either one package set, or a fixed install state."
    have_single_version = right_package_set is None

    if not pnames:
        print("No packages to display.")
        return

    # If we've been asked to sort, then apply the sort to the pnames list, since
    # we use that list's order to print things.
    if sort_comparator is not None:
        entries_to_sort: list[PackageListEntry] = [
            PackageListEntry(
                left_packages=left_package_set.get_pname_packages(pname),
                right_packages=(
                    right_package_set.get_pname_packages(pname)
                    if right_package_set is not None
                    else None
                ),
            )
            for pname in pnames
        ]

        entries_to_sort.sort(key=cmp_to_key(sort_comparator.cmp_packages))

        pnames = [e.get_pname() for e in entries_to_sort]
        del entries_to_sort

    count = 1
    count_width = len(str(len(pnames)))
    count_format_str = "#{:0" + str(count_width) + "d}"
    pname_width = max(len(pname) for pname in pnames)
    pname_format_str = "{:" + str(pname_width) + "}"

    for pname in pnames:
        left_versions = left_package_set.get_pname_versions(pname)
        assert left_versions, f"No left versions available for pname: {pname!r}"

        if have_single_version:
            install_state_str = fixed_install_state
        else:
            right_versions = right_package_set.get_pname_versions(pname)
            assert right_versions, f"No right versions available for pname: {pname!r}"

            if left_versions[-1] < right_versions[0]:
                install_state_str = INST_UPGRADED
            elif left_versions[0] > right_versions[-1]:
                install_state_str = INST_DOWNGRADED
            else:
                install_state_str = INST_CHANGED

        selected_at_all = (
            selected_sets.get_left_set() is not None
            and selected_sets.get_left_set().contains_pname(pname)
        ) or (
            selected_sets.get_right_set() is not None
            and selected_sets.get_right_set().contains_pname(pname)
        )
        if selected_at_all:
            bold_if_selected_sgr = sgr(SGR_BOLD)
            pname_sgr = bold_if_selected_sgr + sgr(SGR_FG + SGR_GREEN + SGR_BRIGHT)
        else:
            bold_if_selected_sgr = ""
            pname_sgr = bold_if_selected_sgr + sgr(SGR_FG + SGR_GREEN)

        versions_common_prefix_len: Optional[int]
        if have_single_version or version_highlight == VERSION_HIGHLIGHT_NONE:
            versions_common_prefix_len = None
        else:
            versions_common_prefix_len = find_common_version_prefix_lists(
                [x.text() for x in left_versions if x.text() != ""],
                [x.text() for x in right_versions if x.text() != ""],
            )

        status_str = "[{}{}]".format(
            bold_if_selected_sgr + install_state_str + sgr(SGR_RESET),
            pname_sgr + selected_sets.get_selection_state(pname) + sgr(SGR_RESET),
        )
        count_str = count_format_str.format(count)
        pname_str = pname_format_str.format(pname)
        print("{}  {}  {}  {}{}".format(
            status_str,
            count_str,
            pname_sgr + pname_str + sgr(SGR_RESET),
            render_versions(
                left_versions,
                colour=True,
                version_highlight=version_highlight,
                highlight_from_pos=versions_common_prefix_len,
            ),
            "" if have_single_version else (
                " -> " + render_versions(
                    right_versions,
                    colour=True,
                    version_highlight=version_highlight,
                    highlight_from_pos=versions_common_prefix_len,
                    is_right=True,
                )
            ),
        ))
        count += 1

def find_common_version_prefix(x: str, y: str, limit: Optional[int]) -> int:
    i = 0
    x_len = len(x)
    y_len = len(y)

    while (
            (limit is None or i < limit)
            and i < x_len
            and i < y_len
            and x[i] == y[i]
    ):
        i += 1

    return i

def find_common_version_prefix_lists(*lsts: list[str]) -> int:
    first = True
    i: int = 0
    target: str

    for lst in lsts:
        for x in lst:
            if first:
                target = x
                i = len(x)
                first = False
            else:
                i = find_common_version_prefix(target, x, i)

            if i == 0:
                return 0

    # Rewind to the start of the current alphanumeric span of characters.  It
    # looks weird to show e.g. "1.15 -> 1.17" with only the 5 and 7 highlighted.
    # It's nicer to highlight 15 and 17.
    #
    # Also, we want to rewind from the middle of a number but stop if we reach
    # the end of a preceeding word, or vice versa.  For example, with
    # "1.9.15p2 -> 1.9.15p5", we should just highlight the final digit, not the
    # common "15p" part.  This is consistent with Nix treating numbers and
    # letters as separate chunks.
    if not first and i < len(target) and i > 0 and ALPHANUM_RE.fullmatch(target[i]):
        if DIGIT_RE.fullmatch(target[i]):
            # Rewind only through digits.
            while i > 0 and DIGIT_RE.fullmatch(target[i - 1]):
                i -= 1
        else:
            # Rewind only through letters.
            while (
                i > 0
                and ALPHANUM_RE.fullmatch(target[i - 1])
                and not DIGIT_RE.fullmatch(target[i - 1])
            ):
                i -= 1

    return i

def query_closure_disk_usage_bytes(target: Path) -> Optional[int]:
    # If we don't add "./" to relative paths, then newer nix will interpret the
    # argument as something related to flakes instead.
    target_str = str(target)
    if not target_str.startswith("/"):
        target_str = "./" + target_str

    try:
        stdout = subprocess.run(
            [make_nix_bin_path("nix")]
            + make_extra_experimental_features_args()
            + ["path-info", "--closure-size", target_str],
            stdout=PIPE,
            text=True,
            # Explicitly omitting check=True here, since this function is
            # allowed to fail.
        ).stdout
    except FileNotFoundError:
        sys.stderr.write("nvd: Error, couldn't run 'nix path-info --closure-size'.\n")
        return None

    lines = stdout.rstrip("\n").split("\n")
    if len(lines) != 1:
        return None

    words = lines[0].split()
    return int(words[-1])

BYTES_UNITS = ["KiB", "MiB", "GiB", "TiB", "PiB", "EiB"]

def render_bytes(bytes_size: int) -> str:
    scaled_size: Union[int, float] = bytes_size
    scaled_suffix = "B"

    neg = scaled_size < 0
    if neg:
        scaled_size = -scaled_size

    for suffix in BYTES_UNITS:
        if scaled_size >= 1024:
            scaled_size /= 1024
            scaled_suffix = suffix
        else:
            break

    if neg:
        scaled_size = -scaled_size

    if isinstance(scaled_size, int):
        return f"{scaled_size:+,d}{scaled_suffix}"  # B (bytes).
    else:
        return f"{scaled_size:+,.1f}{scaled_suffix}"  # KiB or higher.

def make_nix_bin_path(exe_name: str) -> str:
    global NIX_BIN_DIR
    if NIX_BIN_DIR:
        return os.path.join(NIX_BIN_DIR, exe_name)
    else:
        return exe_name

def make_extra_experimental_features_args() -> list[str]:
    global USE_NIX_COMMAND_FEATURE
    if USE_NIX_COMMAND_FEATURE:
        return ["--extra-experimental-features", "nix-command"]
    else:
        return []

def query_nix_version() -> Version:
    output = subprocess.run(
        [make_nix_bin_path("nix-build"), "--version"],
        stdout=PIPE,
        text=True,
        check=True,
    ).stdout

    first_line = output.split("\n", 1)[0]

    words = first_line.split(" ")
    regex = re.compile(r"^[0-9]+\.[0-9]")
    for word in words:
        if regex.search(word):
            return Version(word)

    raise RuntimeError(
        "Could not determine Nix version from 'nix-store --version' output: {output!r}")

def read_symlink_chain(start_path: Path) -> List[Path]:
    link_chain = [start_path]

    current_path = start_path
    while True:
        try:
            link_target = current_path.readlink()
        # If path does not exist or is not a symlink, we've reached the end of the chain
        except (FileNotFoundError, OSError):
            break

        if link_target in link_chain:
            raise RuntimeError(f"Symlink loop detected: {link_chain} -> {link_target}")

        if not link_target.is_absolute():
            link_target = (current_path.parent / link_target)

        link_chain.append(link_target)
        current_path = link_target

    return link_chain

def is_profile_link(path: Path) -> bool:
    match = PROFILE_LINK_REGEX.match(str(path))
    return match is not None

def is_link_to_profile(path: Path, profile_name: str) -> bool:
    match = PROFILE_LINK_REGEX.match(str(path))
    return match is not None and match.group("profile") == profile_name

def make_profile_generation_list(profile_link: Path, minimum_version: int) -> List[ProfileVersion]:
    profile_name = PROFILE_LINK_REGEX.match(str(profile_link)).group("profile")
    all_profile_links = [l for l in profile_link.parent.iterdir() if is_link_to_profile(l, profile_name)]
    all_profile_versions = [ProfileVersion(l) for l in all_profile_links]
    all_profile_versions.sort()
    profile_versions = [pv for pv in all_profile_versions if pv.version() >= minimum_version]

    if len(profile_versions) < 1:
        sys.stderr.write(f"Profile {profile_name} has no versions >= {minimum_version}.\n")
        sys.stderr.write(f"Available versions: {[pv.version() for pv in all_profile_versions]}\n")
        sys.exit(1)

    return profile_versions

def run_list(
    *,
    root,
    only_selected,
    name_patterns,
    sort_comparator: PackageListEntryComparator,
    version_highlight: str,
):
    path = Path(root)

    if not path.exists():
        sys.stderr.write(f"Path does not exist: {path}\n")
        sys.exit(1)

    path = path.resolve()
    if (path / "sw").is_dir():
        selected_set = PackageSet.from_direct_dependencies((path / "sw").resolve())
    else:
        selected_set = PackageSet.from_direct_dependencies(path)

    closure_set = PackageSet.from_closure(path)

    if only_selected:
        target_pnames = list(selected_set.all_pnames())
    else:
        target_pnames = list(closure_set.all_pnames())

    target_pnames = [
        pname
        for pname in target_pnames
        if all(fnmatch.fnmatch(pname, pattern) for pattern in name_patterns)
    ]

    target_pnames.sort()

    print_packages(
        pnames=target_pnames,
        selected_sets=PackageSetPair(selected_set, selected_set),
        left_package_set=closure_set,
        right_package_set=None,
        fixed_install_state=INST_INSTALLED,
        sort_comparator=sort_comparator,
        version_highlight=version_highlight,
    )

def run_diff(
    *,
    root1,
    root2,
    sort_comparator: PackageListEntryComparator,
    only_selected: bool,
    version_highlight: str,
):
    left_path = Path(root1)
    right_path = Path(root2)

    if not left_path.exists():
        sys.stderr.write(f"Path does not exist: {left_path}\n")
        sys.exit(1)

    if not right_path.exists():
        sys.stderr.write(f"Path does not exist: {right_path}\n")
        sys.exit(1)

    left_resolved = left_path.resolve()
    right_resolved = right_path.resolve()

    print(f"<<< {left_path}")
    print(f">>> {right_path}")

    left_selected_set: Optional[PackageSet] = None
    right_selected_set: Optional[PackageSet] = None

    if (left_resolved / "sw").is_dir() and (right_resolved / "sw").is_dir():
        left_selected_set = PackageSet.from_direct_dependencies((left_resolved / "sw").resolve())
        right_selected_set = PackageSet.from_direct_dependencies((right_resolved / "sw").resolve())
    else:
        left_selected_set = PackageSet.from_direct_dependencies(left_resolved)
        right_selected_set = PackageSet.from_direct_dependencies(right_resolved)

    selected_sets = PackageSetPair(left_selected_set, right_selected_set)

    left_closure_set = PackageSet.from_closure(left_resolved)
    right_closure_set = PackageSet.from_closure(right_resolved)

    left_closure_all_package_names = set(left_closure_set.all_pnames())
    right_closure_all_package_names = set(right_closure_set.all_pnames())

    left_selected_package_names = set(left_selected_set.all_pnames())
    right_selected_package_names = set(right_selected_set.all_pnames())

    # Compute changes to versions and selection states.
    pnames_selected_in_either_closure = left_selected_package_names | right_selected_package_names
    pnames_in_both_closures = left_closure_all_package_names & right_closure_all_package_names

    package_names_with_changed_versions = []
    package_names_with_changed_selection_states = []
    for pname in pnames_in_both_closures:
        if only_selected and pname not in pnames_selected_in_either_closure:
            continue

        if left_closure_set.get_pname_versions(pname) != right_closure_set.get_pname_versions(pname):
            package_names_with_changed_versions.append(pname)
        elif selected_sets.is_selection_state_changed(pname):
            package_names_with_changed_selection_states.append(pname)

    # Compute added and removed packages.
    added_package_names = right_closure_all_package_names - left_closure_all_package_names
    removed_package_names = left_closure_all_package_names - right_closure_all_package_names
    if only_selected:
        added_package_names &= pnames_selected_in_either_closure
        removed_package_names &= pnames_selected_in_either_closure

    any_changes_displayed = False

    # Announce version changes.
    if package_names_with_changed_versions:
        any_changes_displayed = True
        print("Version changes:")
        print_packages(
            pnames=package_names_with_changed_versions,
            selected_sets=selected_sets,
            left_package_set=left_closure_set,
            right_package_set=right_closure_set,
            sort_comparator=sort_comparator,
            version_highlight=version_highlight,
        )

    # Announce specific changes for packages whose versions haven't changed.
    if package_names_with_changed_selection_states:
        any_changes_displayed = True
        print("Selection state changes:")
        print_packages(
            pnames=package_names_with_changed_selection_states,
            selected_sets=selected_sets,
            left_package_set=left_closure_set,
            fixed_install_state=INST_CHANGED,
            sort_comparator=sort_comparator,
            version_highlight=version_highlight,
        )

    # Announce added packages.
    if added_package_names:
        any_changes_displayed = True
        print("Added packages:")
        print_packages(
            pnames=added_package_names,
            selected_sets=selected_sets,
            left_package_set=right_closure_set,  # Yes, this is correct.
            fixed_install_state=INST_ADDED,
            sort_comparator=sort_comparator,
            version_highlight=version_highlight,
        )

    # Announce removed packages.
    if removed_package_names:
        any_changes_displayed = True
        print("Removed packages:")
        print_packages(
            pnames=removed_package_names,
            selected_sets=selected_sets,
            left_package_set=left_closure_set,
            fixed_install_state=INST_REMOVED,
            sort_comparator=sort_comparator,
            version_highlight=version_highlight,
        )

    if not any_changes_displayed:
        print("No version or selection state changes.")

    left_closure_paths_set = set(left_closure_set.all_store_paths())
    right_closure_paths_set = set(right_closure_set.all_store_paths())
    left_only_paths_count = len(left_closure_paths_set - right_closure_paths_set)
    right_only_paths_count = len(right_closure_paths_set - left_closure_paths_set)

    left_closure_disk_usage_bytes: Optional[int] = \
        query_closure_disk_usage_bytes(left_path)
    right_closure_disk_usage_bytes: Optional[int] = \
        query_closure_disk_usage_bytes(right_path)

    if left_closure_disk_usage_bytes is None or right_closure_disk_usage_bytes is None:
        diff_closure_disk_usage_str = ""
    else:
        diff_closure_disk_usage_str = ", disk usage " + \
            render_bytes(right_closure_disk_usage_bytes - left_closure_disk_usage_bytes)

    print(
        f"Closure size: {len(left_closure_paths_set)} -> {len(right_closure_paths_set)} "
        f"({right_only_paths_count} paths added, {left_only_paths_count} paths removed, "
        f"delta {right_only_paths_count - left_only_paths_count:+d}"
        f"{diff_closure_disk_usage_str})."
    )

def run_history(
    *,
    profile,
    minimum_version: int,
    list_oldest: bool,
    sort_comparator: PackageListEntryComparator,
    only_selected: bool,
    version_highlight: str,
):
    profile_path = Path(profile)

    if not profile_path.exists():
        sys.stderr.write(f"Path does not exist: {profile_path}\n")
        sys.stderr.write("On non-NixOS systems, try:\nnvd history --profile ~/.nix-profile\n")
        sys.exit(1)

    symlink_chain = read_symlink_chain(profile_path)

    active_profile_links = [l for l in symlink_chain if is_profile_link(l)]

    if len(active_profile_links) < 1:
        sys.stderr.write(f"No versioned profile link found in chain: {[str(l) for l in symlink_chain]}\n")
        sys.exit(1)

    all_profiles = make_profile_generation_list(active_profile_links[0], minimum_version)

    # Show list of packages in the oldest profile if desired.
    oldest_profile = all_profiles[0]

    if list_oldest:
        print(f"--- Version {oldest_profile.version()}:")
        print(f">>> {oldest_profile.path()}")
        run_list(
            root=oldest_profile.path(),
            only_selected=only_selected,
            name_patterns=[],
            sort_comparator=sort_comparator,
            version_highlight=version_highlight,
        )
    else:
        print(f"Contents of profile version {oldest_profile.version()} were omitted, use --list-oldest to show them.")

    # Show diff between all profiles.
    for [base_profile, displayed_profile] in pairwise(all_profiles):
        print(f"\n--- Version {displayed_profile.version()}:")
        run_diff(
            root1=base_profile.path(),
            root2=displayed_profile.path(),
            sort_comparator=sort_comparator,
            only_selected=only_selected,
            version_highlight=version_highlight,
        )

def parse_args():
    def add_selected_arg(p: argparse.ArgumentParser) -> None:
        p.add_argument(
            "-s", "--selected",
            dest="only_selected",
            action="store_true",
            help="Only show selected packages (direct dependencies).")

    def add_sort_arg(p: argparse.ArgumentParser) -> None:
        p.add_argument(
            "--sort",
            default=DEFAULT_SORT.name(),
            help="Sort order for displayed packages.",
        )

    parser = argparse.ArgumentParser(
        description="Nix/NixOS package version diff tool",
        epilog="See the nvd(1) manual page for more information.",
    )

    parser.add_argument(
        "--version",
        action="version",
        version=f"nvd {NVD_VERSION}",
    )

    parser.add_argument(
        "--color",
        default="auto",
        help="Controls use of colour; one of 'auto', 'never', 'always'.")

    parser.add_argument(
        "--version-highlight",
        default=VERSION_HIGHLIGHT_DEFAULT,
        help="Colour scheme to apply to changed parts of versions.")

    parser.add_argument(
        "--nix-bin-dir",
        default=None,
        help="Optional directory containing nix binaries, overrides path lookup.")

    subparsers = parser.add_subparsers(dest="action")

    diff_parser = subparsers.add_parser(
        "diff",
        help="Diff two Nix store paths and their closures.")
    add_selected_arg(diff_parser)
    add_sort_arg(diff_parser)
    diff_parser.add_argument(
        "root1",
        help="The first Nix store path to compare.")
    diff_parser.add_argument(
        "root2",
        help="The second Nix store path to compare.")

    list_parser = subparsers.add_parser(
        "list",
        help="List packages in the closure of a Nix store path.")
    add_selected_arg(list_parser)
    add_sort_arg(list_parser)
    list_parser.add_argument(
        "-r", "--root",
        default="/run/current-system",
        help="The The Nix store path to work with.")
    list_parser.add_argument(
        nargs="*",
        default=[],
        dest="name_patterns",
        help="Patterns (globs) that must all match package names.")

    history_parser = subparsers.add_parser(
        "history",
        help="Show the history of a Nix profile.")
    add_selected_arg(history_parser)
    add_sort_arg(history_parser)
    history_parser.add_argument(
        "-p", "--profile",
        default="/nix/var/nix/profiles/system",
        help="The Nix profile to work with.")
    history_parser.add_argument(
        "-m", "--minimum-version",
        # link 0 doesn't exist, but might become the "initial" empty state in the future.
        default=1,
        type=int,
        help="Minimum version of this profile to display.")
    history_parser.add_argument(
        "--list-oldest",
        action="store_true",
        help="Additionally list all packages in the first displayed profile."
    )

    return parser.parse_args()

def main():
    global NIX_BIN_DIR
    global USE_NIX_COMMAND_FEATURE
    global USE_COLOUR
    global INST_ADDED
    global INST_REMOVED
    global INST_UPGRADED
    global INST_DOWNGRADED
    global INST_CHANGED

    args = vars(parse_args())
    action = args["action"]
    NIX_BIN_DIR = args["nix_bin_dir"] or None
    USE_COLOUR = \
        args["color"] == "always" \
        or (args["color"] == "auto" and sys.stdout.isatty() and not os.getenv('NO_COLOR'))
    del args["action"]
    del args["nix_bin_dir"]
    del args["color"]

    if USE_COLOUR:
        INST_ADDED = sgr(SGR_FG + SGR_BRIGHT + SGR_GREEN) + INST_ADDED
        INST_REMOVED = sgr(SGR_FG + SGR_BRIGHT + SGR_RED) + INST_REMOVED
        INST_UPGRADED = sgr(SGR_FG + SGR_BRIGHT + SGR_CYAN) + INST_UPGRADED
        INST_DOWNGRADED = sgr(SGR_FG + SGR_BRIGHT + SGR_YELLOW) + INST_DOWNGRADED
        INST_CHANGED = sgr(SGR_FG + SGR_BRIGHT + SGR_MAGENTA) + INST_CHANGED

    if (
        "version_highlight" in args
        and args["version_highlight"] not in ALL_VERSION_HIGHLIGHTS
    ):
        sys.stderr.write(f"nvd: Error, unknown --version-highlight: '{args['version_highlight']}'\n")
        sys.exit(1)

    if "sort" in args:
        args["sort_comparator"] = PackageListEntryCombinedComparator.from_str(args["sort"])
        del args["sort"]

    if action is None:
        print("nvd: Subcommand required, see 'nvd --help'.")
        sys.exit(1)

    # Nix 2.4 and later need "experimental-features: nix-command" in order to
    # use the "nix ..." style commands.
    if Version("2.4") < query_nix_version():
        USE_NIX_COMMAND_FEATURE = True

    {
        "list": run_list,
        "diff": run_diff,
        "history": run_history,
    }[action](**args)

# Importing this module is kinda broken because of the constant initializations
# at the top.
if __name__ == "__main__":
    main()
